/**
 * API route to serve manifest.json
 * This workaround is needed because Vercel may not serve public files correctly
 */
const { NextResponse } = require('next/server');
const fs = require('fs');
const path = require('path');

export async function GET() {
  // Try to read manifest from filesystem first
  const possiblePaths = [
    path.join(process.cwd(), 'public', 'manifest.json'),
    '/var/task/public/manifest.json',
  ];
  
  for (const manifestPath of possiblePaths) {
    try {
      if (fs.existsSync(manifestPath)) {
        const content = fs.readFileSync(manifestPath, 'utf-8');
        const manifest = JSON.parse(content);
        console.log('[API/manifest] Loaded from:', manifestPath, 'Files:', manifest.files?.length || 0);
        return NextResponse.json(manifest, {
          headers: {
            'Cache-Control': 'public, max-age=60',
          },
        });
      }
    } catch (err) {
      console.log('[API/manifest] Could not read from', manifestPath, err.message);
    }
  }
  
  // Fallback: Return embedded manifest data
  // This is generated by: node scripts/generate-manifest.js
  console.log('[API/manifest] Using embedded manifest fallback');
  
  const EMBEDDED_MANIFEST = require('../../../public/manifest.json');
  
  return NextResponse.json(EMBEDDED_MANIFEST, {
    headers: {
      'Cache-Control': 'public, max-age=60',
    },
  });
}
